name: Weekly Data Citations Notebook Run - part 2

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["regular_data_citations_part1.yml"]
    types:
      - completed
    
permissions:
  contents: write

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install papermill ipython ipykernel pandas requests numpy
        
      - name: Run Jupyter Notebook
        run: |
          papermill nerc_dataset_citations_part2.ipynb nerc_dataset_citations_part2_executed.ipynb

      - name: Commit and push results
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add Results/v2/latest_results.json
          git commit -m "Regular action, update latest_results JSON file"
          git push citationNotebook split_notebook
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
