name: Weekly Data Citations Notebook Run - part 1

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # Run every Sunday at midnight

permissions:
  contents: write
    
jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install papermill ipython ipykernel pandas requests numpy
        
      - name: Run Jupyter Notebook
        run: |

          papermill nerc_dataset_citations_part1.ipynb nerc_dataset_citations_part1_executed.ipynb # keep "_executed.ipynb" to see errors

      - name: Commit and push results
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add "Results/Intermediate data/latest_results_scholix.csv" "Results/Intermediate data/latest_results_crossRef.csv" "Results/Intermediate data/latest_results_dataCite.csv"
          git commit -m "Regular action, updates Results/Intermediate data/latest_results_{databaseName}.csv"
          git push https://github.com/NERC-EDS/citationNotebook.git misc_updates_spring24

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
