name: Get NERC DOIs from DataCite

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # Run every Sunday at midnight (UTC)

permissions:
  contents: write
    
jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install papermill ipython ipykernel pandas requests numpy
        
      - name: Run Jupyter Notebook
        run: |

          papermill nerc_dataset_DOIs.ipynb executed_notebooks/nerc_dataset_DOIs.ipynb # nerc_dataset_citations_part1_executed.ipynb # keep "_executed.ipynb" to see errors


      - name: Commit and push results
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add "Results/v3/nerc_datacite_dois.json" "nerc_dataset_DOIs.ipynb" "executed_notebooks/nerc_dataset_DOIs.ipynb"
          git commit -m "Regular action, updates nerc_datacite_dois.json"
          git push https://github.com/NERC-EDS/citationNotebook.git main

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
