name: Weekly Data Citations Notebook Run

on:
  workflow_dispatch:
    
jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install papermill ipython ipykernel pandas requests numpy
        
      - name: Run Jupyter Notebook
        run: |
          papermill nerc_dataset_citations_full_code.ipynb nerc_dataset_citations_full_code_executed.ipynb # keep "_executed.ipynb" to see errors

      - name: Commit and push results
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add Results/v1/latest_results.json nerc_dataset_citations_full_code_executed.ipynb
          git commit -m "Regular action, update latest_results JSON file"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
